# https://self-methods.com/django-docker-easy/ を参考
version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    image: app:hello
    environment:
      MYSQL_DBNAME: practice
      MYSQL_USER: root
      MYSQL_PASSWORD: Mysqluser1!
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    command: >
        bash -c "python3 wait-for-db.py &&
        python3 manage.py migrate &&
        echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@myproject.com', 'password')\" | python3 manage.py shell &&
        python3 manage.py runserver 0.0.0.0:8000 --insecure"
    depends_on:
      - db
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Mysqluser1!
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
